# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\URSA_2020\Playing around with PyQt5\Day 11\imageLoader.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import cv2

filePath = []
index = 0


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.imgLbl = QtWidgets.QLabel(self.centralwidget)
        self.imgLbl.setGeometry(QtCore.QRect(100, 50, 400, 400))
        self.imgLbl.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLbl.setObjectName("imgLbl")

        self.nextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextBtn.setGeometry(QtCore.QRect(350, 490, 100, 20))
        self.nextBtn.setObjectName("nextBtn")

        self.previousBtn = QtWidgets.QPushButton(self.centralwidget)
        self.previousBtn.setGeometry(QtCore.QRect(150, 490, 100, 20))
        self.previousBtn.setObjectName("previousBtn")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.readFile()

        # Function
        self.nextBtn.clicked.connect(self.nextImage)
        self.previousBtn.clicked.connect(self.previousImage)

    def readFile(self):
        if not os.path.exists('images'):
            os.makedirs('images')
        global filePath
        scale_percent = 50
        path = os.path.abspath(os.getcwd())
        for i, filename in enumerate(os.listdir(path)):
            img = cv2.imread(os.path.join(path, filename))
            if img is not None:
                path += f"\images\{i}.png"
                dsize = (400,400)
                output = cv2.resize(img, dsize)
                cv2.imwrite(path, output)
                filePath.append(path)
                path = os.path.abspath(os.getcwd())

        pixmap = QtGui.QPixmap(filePath[0])
        self.imgLbl.setPixmap(pixmap)
        self.imgLbl.setGeometry(QtCore.QRect(100,50, 400, 400))
        self.imgLbl.setAlignment(QtCore.Qt.AlignLeft)

    def nextImage(self):
        global index, filePath
        if (index  == len(filePath) - 1):
            self.error()
            return False
        index += 1
        pixmap = QtGui.QPixmap(filePath[index])
        self.imgLbl.setPixmap(pixmap)
        self.imgLbl.setGeometry(QtCore.QRect(100,50, 400, 400))
        self.imgLbl.setAlignment(QtCore.Qt.AlignLeft)

    def previousImage(self):
        global index, filePath
        if (index  == 0):
            self.error()
            return False
        index -= 1
        pixmap = QtGui.QPixmap(filePath[index])
        self.imgLbl.setPixmap(pixmap)
        self.imgLbl.setGeometry(QtCore.QRect(100,50, 400, 400))
        self.imgLbl.setAlignment(QtCore.Qt.AlignLeft)   

    def error(self):
        errorMessage2 = QtWidgets.QMessageBox()
        errorMessage2.setWindowTitle("Error")
        errorMessage2.setText("Out of Range")
        errorMessage2.setIcon(QtWidgets.QMessageBox.Critical)
        x = errorMessage2.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nextBtn.setText(_translate("MainWindow", "Next"))
        self.previousBtn.setText(_translate("MainWindow", "Previous"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
